### ISSUE TITLE
Mark repository private until March 29, 2022 when picoCTF 2022 is over

### ISSUE THREAD

**Issue by hi-liang** [c4llmeco4ch/pico-CTF-2022-Write-ups#1]
We would greatly appreciate folks refrain from public posting write-ups until the competition is over

**Comment by c4llmeco4ch** [comment]
Sounds good, will shift this to a private repo. Thank you for the heads up

**Comment by c4llmeco4ch** [comment]
Should be private now. Working through these problems has been a blast, so thank you for putting this great event on
